title: <p align="center"> KyungHee Kim </p>

logo: "/images/KakaoTalk_20220119_210207777.jpg"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/hikhloee">GitHub</a>
  </p>
  
  <p align="justify">

  Sungkyunkwan University, Master’s degree, Jan. 2021. - Present. Major in Statistics, Time series.  
  <br><br>  
  Currently I am a researcher at Research Institute of Applied Statistics, Sungkyunkwan University(성균관대학교 응용통계연구소).
  <br><br>
  Duksung Women’s University, Bachelor’s degree, Jan. 2016 - Jan. 2021. Major in Statistics, minor in Computer science.  
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
